kinematics:
  shoulder:
    x: 0
    y: 0
    z: 0.1626286912524587
    roll: -0
    pitch: 0
    yaw: 3.09943066125612e-08
  upper_arm:
    x: 9.959989664399905e-05
    y: 0
    z: 0
    roll: 1.570987432838868
    pitch: 0
    yaw: 1.30704495517954e-06
  forearm:
    x: -0.4250973499913824
    y: 0
    z: 0
    roll: 0.001160688944462685
    pitch: -0.000960918223159067
    yaw: 9.546620503698573e-07
  wrist_1:
    x: -0.3922681222258786
    y: -0.0003403640648952678
    z: 0.1336774412500874
    roll: 0.002546153832663995
    pitch: 0.0006111158265445526
    yaw: -3.228748889485943e-07
  wrist_2:
    x: -2.111138972432465e-06
    y: -0.099684743003946
    z: 5.990643942140186e-05
    roll: 1.570195367907866
    pitch: 0
    yaw: -1.023555376743895e-06
  wrist_3:
    x: 1.421508669241318e-05
    y: 0.09957812954010879
    z: 4.024161888921929e-05
    roll: 1.571200447829148
    pitch: 3.141592653589793
    yaw: -3.141592577119448
  hash: calib_14772130028204177453